language: php
php:
  - '7.1'
  - '7.2'

install:
  - composer install

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/phpstan

after_success:
  - travis_retry php vendor/bin/php-coveralls
